# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  executor:
        name: python/default
        tag: '3.8.6'
  run-tests:
    steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Pytest-tests
            command: |
              python -m pytest 
        -run:
            name: Flake8-tests
            command : |
              flake8 --format=html --htmldir=flake-report --extend-ignore=E251,E501,E712 lettings/ profiles/ oc_lettings_site/

        - persist_to_workspace:
            root: 
            paths:
              - .

  build-image:
    docker:
      - image: circleci/python:3.8.6-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker

      # Image Docker
      - run:
          name: Build-Image
          command: |


      # Push Docker on Docker Hub.
      - run:
          name: Push-Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD" docker.io
            docker push lisa367/oc_lettings_django:latest

  deploy-app:
    docker:
      - image:circleci/python:3.8.6-browsers

    steps:
      - run:
          name: Deploy-Image
          command: curl -X POST -d {} "$HOOK_URL"



workflows:
  build_test_deploy:
    jobs:
      - run-tests
      #- build-image
      #- deploy-app

